// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLpM3JqxzZf77VlqGbG5BBSn8DwJXZM7c',
    appId: '1:298693877607:web:2c586d29e1f4a67e8919c2',
    messagingSenderId: '298693877607',
    projectId: 'wingman-12196',
    authDomain: 'wingman-12196.firebaseapp.com',
    storageBucket: 'wingman-12196.appspot.com',
    measurementId: 'G-WJFNTZ6G0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwu9f20zFQkqsNDyzsuFGl_rpbEdcWGmo',
    appId: '1:298693877607:android:bebf493cef3b4f868919c2',
    messagingSenderId: '298693877607',
    projectId: 'wingman-12196',
    storageBucket: 'wingman-12196.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOMckpWkrPJ6-c4z11bF_FaC1E0PzCAMg',
    appId: '1:298693877607:ios:e7c2251f0ef5056d8919c2',
    messagingSenderId: '298693877607',
    projectId: 'wingman-12196',
    storageBucket: 'wingman-12196.appspot.com',
    iosBundleId: 'com.example.aiBestFriendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOMckpWkrPJ6-c4z11bF_FaC1E0PzCAMg',
    appId: '1:298693877607:ios:e7c2251f0ef5056d8919c2',
    messagingSenderId: '298693877607',
    projectId: 'wingman-12196',
    storageBucket: 'wingman-12196.appspot.com',
    iosBundleId: 'com.example.aiBestFriendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLpM3JqxzZf77VlqGbG5BBSn8DwJXZM7c',
    appId: '1:298693877607:web:b244fde6d2f6340a8919c2',
    messagingSenderId: '298693877607',
    projectId: 'wingman-12196',
    authDomain: 'wingman-12196.firebaseapp.com',
    storageBucket: 'wingman-12196.appspot.com',
    measurementId: 'G-L4JE6E2467',
  );
}
